/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AjouterEtudiant.java
 *
 * Created on 18 mai 2012, 15:07:22
 */
package Gestion.absence.Graphique;

import Gestion.absence.ClasseEntite.Classe;
import Gestion.absence.ClasseEntite.Etudiant;
import Gestion.absence.DAO.DAOClasse;
import Gestion.absence.DAO.DAOEtudiant;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal computer
 */
public class AjouterEtudiant extends javax.swing.JInternalFrame {

    /** Creates new form AjouterEtudiant */
    public AjouterEtudiant() {
        initComponents();
       
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AjouterEtudiant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        gsm = new javax.swing.JTextField();
        login = new javax.swing.JTextField();
        pwd = new javax.swing.JTextField();
        sexe = new javax.swing.JComboBox();
        ajouter = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        classe = new javax.swing.JComboBox();
        niveau = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        branche = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ajouter Etudiant");

        jLabel1.setText("CIN");

        jLabel2.setText("Nom ");

        jLabel3.setText("Prenom");

        jLabel4.setText("Classe");

        jLabel5.setText("Sexe");

        jLabel6.setText("Email");

        jLabel7.setText("GSM");

        jLabel8.setText("Login");

        jLabel9.setText("Password");

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        try {
            List listClasse=new DAOClasse().getClassame();

            for(int i=0;i<listClasse.size();i++)
            {
                classe.addItem(listClasse.get(i));

            }
        } catch (Exception ex) {
            Logger.getLogger(AjouterEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classeActionPerformed(evt);
            }
        });

        niveau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        jLabel10.setText("Niveau");

        branche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informatique", "Electromecanique", "Telecom", "Branche Commune" }));
        branche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brancheActionPerformed(evt);
            }
        });

        jLabel11.setText("Branche");

        javax.swing.GroupLayout AjouterEtudiantLayout = new javax.swing.GroupLayout(AjouterEtudiant);
        AjouterEtudiant.setLayout(AjouterEtudiantLayout);
        AjouterEtudiantLayout.setHorizontalGroup(
            AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(classe, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nom)
                                .addComponent(cin, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(prenom, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(niveau, javax.swing.GroupLayout.Alignment.TRAILING, 0, 177, Short.MAX_VALUE)))
                        .addGap(248, 248, 248))
                    .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addComponent(branche, 0, 189, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexe, 0, 189, Short.MAX_VALUE)
                            .addComponent(pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(gsm, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addGap(104, 104, 104)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajouter))
                        .addGap(67, 67, 67))))
        );
        AjouterEtudiantLayout.setVerticalGroup(
            AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                        .addComponent(reset)
                        .addGap(18, 18, 18)
                        .addComponent(ajouter))
                    .addGroup(AjouterEtudiantLayout.createSequentialGroup()
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(branche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(gsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AjouterEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AjouterEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AjouterEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cinActionPerformed

private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
initComponents();
sexe.setSelectedIndex(0);
classe.setSelectedIndex(0);
}//GEN-LAST:event_resetActionPerformed

private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
Etudiant etudiant;
DAOEtudiant DAOe = new DAOEtudiant();
int cinn = Integer.parseInt(cin.getText());
String name=nom.getText();
String pname= prenom.getText();
String mail = email.getText();
int phone = Integer.parseInt(gsm.getText());
String logg = login.getText();
String pssd = pwd.getText();
String sx = sexe.getSelectedItem().toString();
String cls =(String) classe.getSelectedItem();
int niv = Integer.parseInt(niveau.getSelectedItem().toString());
String brnch = branche.getSelectedItem().toString();
DAOClasse e = new DAOClasse();
Classe c = e.findNomNiveauBra(niv, cls, brnch);
e.toString();
etudiant = new Etudiant(cinn,name,pname,c,sx,mail,phone,logg,pssd);
//DAOe.ajouter(etudiant);

Etudiant var = DAOe.find(cinn);

if (var==null){
     var = new Etudiant();
}
if(var.equals(etudiant)){
    JOptionPane.showMessageDialog(rootPane, "Etudiant Existant dans la base");
}
else {
    DAOe.ajouter(etudiant);
    JOptionPane.showMessageDialog(rootPane, "Etudiant Ajouté a la base");
}

}//GEN-LAST:event_ajouterActionPerformed

private void classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_classeActionPerformed

private void brancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brancheActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_brancheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new AjouterEtudiant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AjouterEtudiant;
    private javax.swing.JButton ajouter;
    private javax.swing.JComboBox branche;
    private javax.swing.JTextField cin;
    private javax.swing.JComboBox classe;
    private javax.swing.JTextField email;
    private javax.swing.JTextField gsm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField login;
    private javax.swing.JComboBox niveau;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField pwd;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox sexe;
    // End of variables declaration//GEN-END:variables
}
