/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAdmin.java
 *
 * Created on 23 mai 2012, 03:44:27
 */
package Gestion.absence.Graphique;

import java.awt.event.ActionEvent;

/**
 *
 * @author Personal computer
 */
public class MenuAdmin extends javax.swing.JFrame {

    /** Creates new form MenuAdmin */
    public MenuAdmin() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        AjouterEtudiantMenuItem = new javax.swing.JMenuItem();
        AjouterProfMenuItem = new javax.swing.JMenuItem();
        AjouterMatiereMenuItem = new javax.swing.JMenuItem();
        AjouterClasseMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrateur");
        setBackground(new java.awt.Color(204, 204, 204));

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        jMenu1.setText("Deconnection");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajouter");

        AjouterEtudiantMenuItem.setText("Etudiant");
        AjouterEtudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEtudiantMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AjouterEtudiantMenuItem);

        AjouterProfMenuItem.setText("Professeur");
        AjouterProfMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProfMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AjouterProfMenuItem);

        AjouterMatiereMenuItem.setText("Matiere");
        AjouterMatiereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterMatiereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AjouterMatiereMenuItem);

        AjouterClasseMenuItem.setText("Classe");
        AjouterClasseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterClasseMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AjouterClasseMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Modifier");

        jMenuItem1.setText("Etudiant");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Professeur");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Classe");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Matiere");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Voir Absences");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Absence par classe");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void AjouterEtudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEtudiantMenuItemActionPerformed
    jDesktopPane1.removeAll();
    AjouterEtudiant ADDe = new AjouterEtudiant();
    jDesktopPane1.add(ADDe);
    ADDe.setVisible(true);
}//GEN-LAST:event_AjouterEtudiantMenuItemActionPerformed

private void AjouterProfMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProfMenuItemActionPerformed
   jDesktopPane1.removeAll();
    AjouterProfesseur ADDp = new AjouterProfesseur();
   jDesktopPane1.add(ADDp);
   ADDp.setVisible(true);
}//GEN-LAST:event_AjouterProfMenuItemActionPerformed

private void AjouterMatiereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterMatiereMenuItemActionPerformed
    jDesktopPane1.removeAll();
    AjoutMatiere ADDm = new AjoutMatiere();
   jDesktopPane1.add(ADDm);
   ADDm.setVisible(true);
}//GEN-LAST:event_AjouterMatiereMenuItemActionPerformed

private void AjouterClasseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterClasseMenuItemActionPerformed
jDesktopPane1.removeAll();
  AjoutClasse ADDc = new AjoutClasse();
jDesktopPane1.add(ADDc);
ADDc.setVisible(true);
}//GEN-LAST:event_AjouterClasseMenuItemActionPerformed

private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
Login Dx = new Login();
Dx.setLocationRelativeTo(null);
Dx.setVisible(true);
this.setVisible(false);
}//GEN-LAST:event_jMenu1MouseClicked

private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked

}//GEN-LAST:event_jMenuItem1MouseClicked

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
jDesktopPane1.removeAll();
ModifierEtudiant ME = new ModifierEtudiant();
jDesktopPane1.add(ME);
ME.setVisible(true);
this.setVisible(true);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

}//GEN-LAST:event_jMenu3ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
jDesktopPane1.removeAll();
AbsenceByClasse aa = new AbsenceByClasse();
jDesktopPane1.add(aa);
aa.setVisible(true);
this.setVisible(true);
}//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MenuAdmin frame =new MenuAdmin();
                frame.setSize(800,650);
                frame.setLocationRelativeTo(null);
                frame.show(); 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjouterClasseMenuItem;
    private javax.swing.JMenuItem AjouterEtudiantMenuItem;
    private javax.swing.JMenuItem AjouterMatiereMenuItem;
    private javax.swing.JMenuItem AjouterProfMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
